### PR TITLE
IOS Swift migration

### PR DESCRIPTION
**Pull request by cristianoccazinsp**
- Migrated View code to Swift
- Fixed podspec compile issue
- Include error text/info in error callback

With the codebase being in swift, there's no need to some of the conditional header imports. However, a full clean + build may be required after a pod install to remove old artifacts.

### CODE REVIEW

**Review by rodymolenaar — APPROVED** [review]
Nice work! I'm not so sure why the hardcoded package name is needed in the Podspec, can you give some more details on it?

**Comment by cristianoccazinsp** [comment]
I think it can't contan "@ ... /" characters, since that's what the pod will then use to link the project and stuff. 

The requirement is basically that the pod name matches the podspec file, I believe.  Feel free to test other naming alternatives, but when I looked at other RN packages, that also seemed to be the pattern.

**Comment by rodymolenaar** [comment]
> I think it can't contan "@ ... /" characters, since that's what the pod will then use to link the project and stuff. 
> 
> The requirement is basically that the pod name matches the podspec file, I believe.  Feel free to test other naming alternatives, but when I looked at other RN packages, that also seemed to be the pattern.

Ah okay. Just wanted to check!

Feel free to merge once you're ready.

**Comment by cristianoccazinsp** [comment]
Can you tell me a bit more about the steps required to test this when installed directly with npm from a git repository? I cannot seem to get the "dist" folder to get built. I wanted to give it one last test before merging, but installing from git doesn't work due to the build steps.

**Comment by rodymolenaar** [comment]
> Can you tell me a bit more about the steps required to test this when installed directly with npm from a git repository? I cannot seem to get the "dist" folder to get built. I wanted to give it one last test before merging, but installing from git doesn't work due to the build steps.

The build step is generating the JavaScript and types from the TypeScript source. You can choose to run `yarn && yarn build` inside node-modules/@lightbase/react-native-panorama-view or use `yarn link` to connect a local repo to your project and run `yarn build` there.

Not sure what the equivalents are for NPM.

**Comment by cristianoccazinsp** [comment]
I think I got it, I still had to run the build step and manually copy the dist folder into my node_modules own project. I guess that's acceptable at least until it is published to npm. Thanks!

**Review by rodymolenaar — CHANGES_REQUESTED** [review]
Please use yarn for installing package dependencies, otherwise we'll get two conflicting lock files.

Also, are you sure the onImageLoadingFailed event is also passed from Android?

What is the purpose of adding it? I'd love for the library to be typed properly so I'm curious for what the reason is.

**Comment by cristianoccazinsp** [comment]
Since one of the changes included before was to be able to download images remotely, it makes sense to now return some extra info / messages when the loading fails.  You are right about the Android counterpart, totally overlooked that one!

Do you think there's no point in returning the reason behind a load failure?

**Comment by rodymolenaar** [comment]
> Since one of the changes included before was to be able to download images remotely, it makes sense to now return some extra info / messages when the loading fails. You are right about the Android counterpart, totally overlooked that one!
> 
> Do you think there's no point in returning the reason behind a load failure?

I'm totally for providing more information on why an error occured, but maybe we should implement it in a way that is the same for both Android & iOS.

For example, a network connection loss error might be completely different between the two. So a user would have to write a bunch of code just to use the extra information.

**Comment by cristianoccazinsp** [comment]
That makes sense. Then the error should probably be a code string or something.

**Comment by cristianoccazinsp** [comment]
I've reverted the error message change on the JS/TS side in order to work on that later, but left the native side initial work for both Android (new) and iOS. Could use some help thinking in the error codes since iOS and Android paths can be different :)

Also removed the lock file.

**Comment by chernandezq** [comment]
You can review this, I have problems with the pod installation `[!] No podspec found for `@lightbase` in `../node_modules/@lightbase/react-native-panorama-view``

**Comment by cristianoccazinsp** [comment]
In this PR I technically fixed the podspec error.

**Comment by chernandezq** [comment]
@cristianoccazinsp How I can reply to this solution on my local machine? I already changed the ios of your commits files in my local node_modules but I have the same error, can you help me

**Comment by cristianoccazinsp** [comment]
Install directly from git. Add to package.json:

"@lightbase/react-native-panorama-view": "github:lightbasenl/react-native-panorama-view#swift-migration",

You will most likely need to also build the TS files and copy them into the dist folder.

For me the podspec change worked fine. Make sure to clean the the xcode project, and also pod install. From the error above, you are still using the old podspec file.

**Comment by cristianoccazinsp** [comment]
@rodymolenaar do you think it is good to merge now? Probably good idea to do another canary release with this so pod install issues are resolved too. An important step is to clean iOS' build folder from XCode.

**Review by rodymolenaar — APPROVED** [review]

**Comment by rodymolenaar** [comment]
This PR has been merged and 1.0.0-canary.1 released

**Pull request merged**
